title: Ministry of Law - Licensing & Regulation of Insolvency Practitioners
description: Description
url: https://lripd.mlaw.gov.sg
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
favicon: /images/favicon-mlaw.ico
google-analytics: null
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://staging.d1wiic2pv6dub5.amplifyapp.com/
prod: https://master.d1wiic2pv6dub5.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: "#a40935"
  secondary-color: "#a40935"
  media-colors:
    - title: media-color-one
      color: "#696969"
    - title: media-color-two
      color: "#800000"
    - title: media-color-three
      color: "#A0522D"
    - title: media-color-four
      color: "#866633"
    - title: media-color-five
      color: "#505050"
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
